Repository sourcegrade/jagr, pull requests merged in 2022-11, with the labels that each got.

#153 Fix missing Set serialization for child process mode
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SerializerFactory.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SourceSetInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SubmissionInfo.kt
Labels: semver:patch, size:S

#154 Fix libs task not recursively checking dependencies for parent grader
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderLibsTask.kt
Labels: semver:patch, size:S

#164 Only show first error message when multiple test results present
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/JUnitTestRefFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/TestExecutionMessaging.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/grader/TestAwareGraderImpl.kt
Labels: semver:patch, size:S

#165 Fix logging error on startup with jagr-gradle
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch, size:S

#169 Fix type insns not being renamed in ClassRenamingTransformer
  core/src/main/kotlin/org/sourcegrade/jagr/core/transformer/ClassRenamingTransformer.kt
Labels: semver:patch, size:S

#173 Fix ClassRenamingTransformer not renaming descriptors and fields
  core/src/main/kotlin/org/sourcegrade/jagr/core/transformer/ClassRenamingTransformer.kt
Labels: semver:patch, size:S

#174 Format text inside [[[...]]] as code in HTML export
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/BasicHTMLExporter.kt
Labels: semver:patch, feature request, size:S

#177 Do not hardcode jagr version in exported main buildscript
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
  core/src/main/resources/org/gradle/build.gradle.kts_
Labels: semver:patch, size:S

#178 Fix missing dependencies in gradle export
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
Labels: semver:patch, size:S

#179 Fix graderRun task failing even when all points still reachable
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch, size:S

#180 Reset timeout before each test
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaRuntimeTester.kt
Labels: semver:patch, size:S

#182 Improve grader run task logging and failure message
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch, size:S

#181 Use naming scheme with submission information for HTML export
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/BasicHTMLExporter.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:minor, size:S

#183 Fix total timeout not being triggered correctly
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/TimeoutHandler.kt
Labels: semver:patch, size:S

#188 Fix GraderRunTask not respecting grader configuration precedence
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch, size:S
