Repository sourcegrade/jagr, pull requests merged in 2022-10, with the labels that each got.

#120 Improve dependency configuration via jagr-gradle
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/Unpack.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/AbstractConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/DependencyConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/WriteInfoTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderWriteInfoTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionWriteInfoTask.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/AssignmentArtifactInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/RepositoryConfiguration.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SubmissionInfo.kt
Labels: major

#121 Improve sourceSets in grader and submission info json
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderJarImpl.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/SourceSetExtensions.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/AbstractConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderWriteInfoTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionWriteInfoTask.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/AssignmentArtifactInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SourceSetInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SubmissionInfo.kt
Labels: major

#127 Rework LaunchConfiguration and remove configurate dependency in core
  core/build.gradle.kts
  core/src/main/kotlin/org/sourcegrade/jagr/core/CommonModule.kt
  gradle/libs.versions.toml
  launcher/build.gradle.kts
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/env/Config.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/env/LaunchConfiguration.kt
Labels: major

#128 Support custom config via gradle
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/GraderConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GradleLaunchConfiguration.kt
Labels: minor

#126 Fix gradle logging error with custom log4j2 config
  launcher/gradle-plugin/build.gradle.kts
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GradleLaunchConfiguration.kt
  launcher/src/main/resources/log4j2-child.xml
  launcher/src/main/resources/log4j2-console-only.xml
  launcher/src/main/resources/log4j2.xml
Labels: patch

#130 Add logo and update readme
  README.md
  logo.svg
Labels: documentation

#133 Add ClassTransformer.injectSuperclass
  core/src/main/kotlin/org/sourcegrade/jagr/core/transformer/ClassTransformerFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/transformer/InjectSuperclassTransformer.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/ClassTransformer.java
Labels: minor

#137 Fix broken file path separators on windows for grader run task
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/SourceSetExtensions.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch

#139 Fix broken capitalization in some locals by forcing english capitalization
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/AbstractConfiguration.kt
Labels: semver:patch, size:S

#143 Let JUnitTestRefFactoryImpl.Default.get evaluate all matching test results instead of only the first
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/JUnitTestRefFactoryImpl.kt
Labels: semver:patch, size:S

#141 Make the link to the result.html file clickable inside the console on Windows
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
Labels: semver:patch, size:S

#147 Fix HTML Escaping
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/BasicHTMLExporter.kt
Labels: semver:patch

#146 Add skipCompilationCheck() to skip compileJava on buildSubmission
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/SubmissionConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderWriteInfoTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionWriteInfoTask.kt
Labels: semver:minor, size:S

#148 Check child tests for failtures
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/JUnitTestRefFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/TestStatusListenerImpl.kt
Labels: semver:patch, size:M

#149 Remove RubricForSubmission and TestForSubmission deprecations from v0.6
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderJarImpl.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/RubricForSubmission.java
  grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/RubricProvider.java
  grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/TestForSubmission.java
Labels: semver:major, size:S
