Repository sourcegrade/jagr, pull requests merged in 2022-09, with the labels that each got.

#97 Add style plugin
  build.gradle.kts
  gradle/libs.versions.toml
Labels: patch

#98 Search in-memory ClassLoader for jagr packages
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/java/ExtendedStandardJavaFileManager.kt
Labels: patch

#99 Clean and improve GraderJar logging
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderJarImpl.kt
Labels: patch

#100 Search correct parent classloader in findClass(String)
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/java/RuntimeClassLoader.kt
Labels: patch

#101 Force single assignmentId in grader jar
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/BatchCompilation.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderInfoImpl.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
Labels: major

#108 Remove GraderInfoImpl and SubmissionInfoImpl
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/InfoJsonResourceExtractor.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/ResourceCollector.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/BatchCompilation.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/MoodleJSONExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/EclipseSubmissionExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/Unpack.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/io/SerializationFactoryLocatorImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/FallbackRuntimeTester.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderInfoImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaRuntimeTester.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaSubmission.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/SourceSetInfoImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/TestStatusListenerImpl.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/Submission.java
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/SubmissionInfo.java
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SafeStringSerializer.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SourceSetInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SubmissionInfo.kt
Labels: major

#110 Add option to specify custom export build script
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/RubricConfigurationImpl.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/RubricConfiguration.java
Labels: minor

#111 Add jagrVersion field to GraderInfo
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
Labels: major

#112 Remove SLF4J and move to log4j api
  core/build.gradle.kts
  core/src/main/kotlin/org/sourcegrade/jagr/core/CommonModule.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/java/JavaCompiledContainer.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/java/RuntimeJarLoader.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/BatchCompilation.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/GradingQueueFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/GradingQueueImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/executor/TimeoutHandler.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/GermanCSVExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/rubric/MoodleJSONExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/ExtrasManagerImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/MoodleUnpack.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/Unpack.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/JUnitTestRefFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/grader/DescendingPriorityGrader.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/rubric/grader/GraderFactoryImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderJarImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaRuntimeTester.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/RuntimeGraderImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/TestStatusListenerImpl.kt
  gradle/libs.versions.toml
  launcher/build.gradle.kts
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/env/Jagr.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/env/LaunchConfiguration.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/executor/ProcessWorker.kt
  src/main/kotlin/org/sourcegrade/jagr/Files.kt
Labels: major

#113 Ship version file and log version on startup
  launcher/build.gradle.kts
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/env/Jagr.kt
  src/main/kotlin/org/sourcegrade/jagr/StandardGrading.kt
Labels: minor

#114 Add jagrVersion field to SubmissionInfo
  core/src/main/kotlin/org/sourcegrade/jagr/core/extra/Unpack.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/SubmissionInfo.kt
Labels: major

#106 Add jagr-gradle plugin
  gradle/libs.versions.toml
  launcher/gradle-plugin/build.gradle.kts
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/JagrGradlePlugin.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/SourceSetExtensions.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/AbstractConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/GraderConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/JagrExtension.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/SubmissionConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/JagrTaskFactory.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/TargetAssignmentTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/TargetSourceSetsTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderBuildTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderLibsTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderRunTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderWriteInfoTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionBuildTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionTask.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/submission/SubmissionWriteInfoTask.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/RubricLogging.kt
  settings.gradle.kts
  src/main/kotlin/org/sourcegrade/jagr/StandardGrading.kt
Labels: minor

#118 Add rubricClassName to grader info
  core/src/main/kotlin/org/sourcegrade/jagr/core/export/submission/GradleSubmissionExporter.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/FallbackRuntimeTester.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/FallbackTestCycle.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/GraderJarImpl.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaRuntimeTester.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/JavaTestCycle.kt
  core/src/main/kotlin/org/sourcegrade/jagr/core/testing/RuntimeGraderImpl.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/RubricForSubmission.java
  grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/TestForSubmission.java
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/TestCycle.java
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/extension/GraderConfiguration.kt
  launcher/gradle-plugin/src/main/kotlin/org/sourcegrade/jagr/gradle/task/grader/GraderWriteInfoTask.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderInfo.kt
  launcher/src/main/kotlin/org/sourcegrade/jagr/launcher/io/GraderJar.kt
Labels: major

#119 Add visitClass to RuntimeClassLoader
  core/src/main/kotlin/org/sourcegrade/jagr/core/compiler/java/RuntimeClassLoaderImpl.kt
  grader-api/src/main/java/org/sourcegrade/jagr/api/testing/RuntimeClassLoader.java
Labels: minor
